### ISSUE TITLE
How to register multiple interfaces with only 1 singleton instance

### ISSUE THREAD

**Issue by duannl** [fluttercommunity/get_it#157]
For example, I want to register multiple interfaces: `DatabaseReadable`, `DatabaseWritable` with only 1 singleton of `DatabaseImpl`. Does the code below work?
```
getIt.registerSingleton<DatabaseReadable>(DatabaseImpl());
getIt.registerSingleton<DatabaseWritable>(DatabaseImpl());
```

**Comment by escamoteur** [comment]
Yep, that's absolutely ok

**Comment by duannl** [comment]
@escamoteur Thanks. Hope you’re having a great day 😊

**Comment by Frank-D** [comment]
Maybe it’s trivial for some, but I just wanted to point out that as per the code example provided above, unless the DatabaseImpl class is truly implemented following the [Singleton Pattern](https://stackoverflow.com/a/55348216)  (this has nothing to do with GetIt), the code above would be generating 2 instances of the DatabaseImpl class, not one like it is expected (as per the GetIt singleton method name suggests..), since the DatabaseImpl() constructor will effectively be called twice.

**Comment by escamoteur** [comment]
No, it does what it says. It registers two Singletons that share the same code. you will always get the correct instance when querying with getit for the interface type.

**Comment by Frank-D** [comment]
@escamoteur correct, but let me put this in a other way then: how would you go with mapping 2 different interfaces for the same one unique singleton instance of an implementing class? 

(that’s actually my current use case/requirement, to be able to call getIt from different locations in my code, and calling it with different interfaces to limit the number of methods accessible to match the context of where getIt is being called, bu in the end, obtain always the same unique singleton and not different instances of the same impl class..)

The only way I can think of right now, is to do like I suggested in my previous comment, which means, same code as per the very first comment above, but making sure that the DatabaseImpl implementing class (..of the various interfaces) is internally defined as a singleton, so that, it doesn’t matter how many times its constructor DatabaseImpl() is called when doing those multiple getIt registration calls for each interface to be mapped, it will always return the same single instance (the singleton) and so getIt will end up with different/multiple interfaces mapped to the same unique singleton instance, and not multiple instances of the same code like you mentioned.

Do you see any issue with that approach, or any better way to implement this many-interfaces-to-one-impl-instance with getIt?
