### ISSUE TITLE
Now that I've learned enough to understand it ...

### ISSUE THREAD

**Issue by richardhaven** [fluttercommunity/get_it#168]
I really like the lightweight and direct design

If you are getting any resistance because you use the word, "Singleton", please consider adding synonyms like registerInstance()

Have you considered a testing protocol where one can register a class rather than a normal instance?

Please consider adding separate methods when one searches (or registers) by name instead of type. I'm very old-school and expecting XOR parameters hurts [s]

Have you heard of anyone using Get_It for a state-management solution?

Cheers

**Comment by escamoteur** [comment]
Hi Richard,
I have done enough discussions about the problems that singletons are said to be having. So it doesn't bother me really.
I don't understand what you mean the testing protocol where one can register a class could you elaborate on this?

Actually you always have to provide type now even if you provide a name so providing a name is the optional version. I'm not sure what you mean with expecting acts or parameters?

Sure I have heard from several people using get_it as state management solutions. I have actually written another package because they get_it_mixin that makes state management with get the breeze. Check it out and tell me what you think.
