### ISSUE TITLE
Register registerFactoryParam or registerFactoryParamAsync method only allow T as object, it will not accept nullable T

### ISSUE THREAD

**Issue by Ted-chiptech** [fluttercommunity/get_it#182]
Could we consider the factory could return Null case?
At the moment, it doesn't accept registering any Nullable type for the factory because that type won't be extended from Object, it extends from Object?

Example:
```
sl.registerFactoryParam<Foo?, Param1 void>(
    (param1, _) => FooFactory.getFooByParam1(param1!),
  );
```
can't be done.

**Comment by escamoteur** [comment]
in my opinion that the whole point of making code null safe. Could you elaborate why you would need the ability for factory to return null?

**Comment by Ted-chiptech** [comment]
Sure, in my case is the factory consumes a shared enum type and returns an object base on that type, but for some enum values, it needs to return null if the factory doesn't know how to create the object base on that type.  Another way to solve it could be creating a dedicated enum type or default return object for the factory, but it will require duplicating some enum type values.

I think null safe is to guard the code when the null is not expected if we didn't set the type to nullable, but for my case, I do expect the factory to return null if it couldn't produce the object base on those knowing information (as I will need to specify the return object is nullable), and I think factory probably don't need to guard the result is never gonna be null as it could leave the factory author to make that decision by specifying the return object is nullable to not?

```
// This enum is shared by others too.
enum FooType{ fooType1, fooType2, fooType3, fooType4}

class FooFactory {
  static FooObject?
      getFooByFooType(
          FooType) {
    switch (FooType) {
      case FooType.fooType1:
        return Foo1();
      case FooType.fooType2:
        return Foo2();
      default:
        return null;
    }
  }
}
```

**Comment by escamoteur** [comment]
Indeed there are 2 ways to solve this without resorting to null:

1. Define a special FooObject derived class type that signals an error condition
2. Thrown exception 

If we had discriminated union types already in Dart it would be even easier.

I'm currently hesitating a bit to open up the null safety here.

I just played it through in the code and the problem is I can't relax the constraint on T from extending object because this would force that `get()` would no longer guarantee to return null safe values, which meant you would have to place ? or ! everywhere you access a value inside GetIt.

See the definition of `get()``:
![image](https://user-images.githubusercontent.com/16635729/116520183-ac2a8b80-a8d2-11eb-9d0b-775a1504ca13.png)
