### ISSUE TITLE
Could anyone pls add more functions to add multiple parameters instead of upto two

### ISSUE THREAD

**Issue by majidflutter** [fluttercommunity/get_it#268]
we have **registerFactoryParam** function which accepts up to two parameters but I want to add 5,6 parameters to my model and register via **GETIT**  but for now, I am not seeing any option to do this, could anyone add a new function which can accept **N** number of parameters so to anyone add parameters according to his own need 

my second query is, ho  **registerFactoryParam**   function will impact object life, if I register my whole app instances in **GETIT** at the start,  Will it manage their life cycles ?  I mean when not required should be disposed of that particular object and when needed again initialize so that memory can be managed

**Comment by escamoteur** [comment]
Hi,

the obvious answer for your problem is wrap your parameters into a class and pass it in an ojbect as one parameter. Dart does not allow to pass n-parameters.

To your second question: No, get_it doesn't remove objects from memory automativally. If you use `registerLazySingleton` you can call `resetLazySingleton` this will allow the garbage collector to free the instance given that no other reference of you points to it. 
Also get_it scopes help managing the lifetime a lot.
