### ISSUE TITLE
How I can get a lazySinglton from another isolate

### ISSUE THREAD

**Issue by Reekoooo** [fluttercommunity/get_it#57]
suppose I registered a repo like this

 ```
sl.registerLazySingleton<CalenderMonthRepository>(()=>CalenderMonthRepositoryImpl(
    local: sl(),
    remote: sl(),
    location: sl(),
    notificationsDataSource: sl(),
```

all local, remote,location and notificationsDataSource are lazySingletons too,

I have this static function

```
static Future<CalenderMonth> getCalenderMonth(CalenderMonthRepository repository ) async{
//use repository
  }
```

and I am calling compute function like this

`CalenderMonth calenderMonth= await compute(getCalenderMonth,repository);
`

the issue is when I pass it to another isolate via dart compute function which should run on another isolate I get error of not reachable code .

the question is how to use lazySingletons like these on other isolates ?

**Comment by escamoteur** [comment]
You cannot that's a limitation of flutter. Am 18.03.2020 17:06 schrieb Reekoooo <notifications@github.com>:
suppose I registered a repo like this
sl.registerLazySingleton<CalenderMonthRepository>(()=>CalenderMonthRepositoryImpl(
   local: sl(),
   remote: sl(),
   location: sl(),
   notificationsDataSource: sl(),

all local, remote,location and notificationsDataSource are lazySingletons too,
I have this static function
static Future<CalenderMonth> getCalenderMonth(CalenderMonthRepository repository ) async{
//use repository
  }

and I am calling compute function like this
CalenderMonth calenderMonth= await compute(getCalenderMonth,repository); 
the issue is when I pass it to another isolate via dart compute function which should run on another isolate I get error of not reachable code .
the question is how to use lazySingletons like these on other isolates ?

**Comment by Reekoooo** [comment]
Thank you for your quick response, if it permissible to far extend this discussion by asking two couple more questions it will be great ,

first: if I used regiterSingleton instead it will be OK?
second: Is it possible to initialize another instance of getit in another isolate ? if yes how to do that?

**Comment by escamoteur** [comment]
1. No, it still won't work
2. you should be able to use https://pub.dev/documentation/get_it/latest/get_it/GetIt/GetIt.asNewInstance.html
